### ISSUE TITLE
New package name

### ISSUE THREAD

**Issue by Siggiboy21** [Traurige/libKitten#3]
New package name I cant install diary because of the new name

**Comment by Traurige** [comment]
Diary is archived and unmaintained like most of my other tweaks. That means their dependencies won’t change any time soon. libKitten recently received a pull request to implement the old identifier as well, but I haven’t published a release yet. You can modify either tweak’s control file and compile them yourself, or wait until I publish the libKitten update. Perhaps i’ll do that in my break now 💁🏼‍♀️
